# Cloud Build configuration for Consumption Dashboard
# This file is used by Google Cloud Build to deploy to Cloud Run

steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/consumption-dashboard:$BUILD_ID'
      - '-t'
      - 'gcr.io/$PROJECT_ID/consumption-dashboard:latest'
      - '.'
    id: 'build-image'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/consumption-dashboard:$BUILD_ID'
    id: 'push-image-build-id'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/consumption-dashboard:latest'
    id: 'push-image-latest'

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'consumption-dashboard'
      - '--image'
      - 'gcr.io/$PROJECT_ID/consumption-dashboard:$BUILD_ID'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--timeout'
      - '300'
      - '--set-env-vars'
      - 'GCP_PROJECT_ID=yotam-395120,BQ_DATASET_ID=peerplay'
    id: 'deploy-cloud-run'

# Images to be pushed to the Container Registry
images:
  - 'gcr.io/$PROJECT_ID/consumption-dashboard:latest'

# Build timeout
timeout: '1200s'

# Options
options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

